# Generated by Django 4.2.4 on 2023-08-28 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transport',
            options={'verbose_name_plural': 'Транспорт'},
        ),
        migrations.RenameField(
            model_name='transport',
            old_name='name',
            new_name='Название',
        ),
    ]
