# Generated by Django 4.2.4 on 2023-08-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_transport_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='Название',
        ),
        migrations.AddField(
            model_name='transport',
            name='name',
            field=models.CharField(default='', max_length=1024, verbose_name='Название'),
        ),
    ]
