# Generated by Django 4.2.4 on 2023-08-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_company_device_transport_company_transport_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='transport_img',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
    ]
