# Generated by Django 4.2.4 on 2023-08-28 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_transport_transport_img_act'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='act',
            options={'verbose_name_plural': 'Акты'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name_plural': 'Устройства'},
        ),
        migrations.AlterField(
            model_name='act',
            name='description',
            field=models.TextField(default='', max_length=4095, verbose_name='Описание работ'),
        ),
        migrations.AlterField(
            model_name='act',
            name='executor',
            field=models.CharField(default='', max_length=1024, verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='act',
            name='transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.transport', verbose_name='Транспорт'),
        ),
        migrations.AlterField(
            model_name='company',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default='', max_length=1024, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='device',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания'),
        ),
        migrations.AlterField(
            model_name='device',
            name='imei',
            field=models.CharField(default='', max_length=1024, verbose_name='IMEI'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(default='', max_length=1024, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.device', verbose_name='Устройство'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='name',
            field=models.CharField(default='', max_length=1024, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='transport_img',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='vin',
            field=models.CharField(default='', max_length=1024, verbose_name='VIN номер'),
        ),
    ]
