# Generated by Django 4.2.4 on 2023-08-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_transport_vin'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, default='2023-01-01 00:00:00 ', verbose_name='Дата и время создания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transport',
            name='transport_img',
            field=models.ImageField(blank=True, default='', null=True, upload_to='static/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='vin',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='VIN номер'),
        ),
    ]
